version: '3'
services:
  camcamdocker: 
    image: camcam:latest
    container_name: camcam
    user: node
    ports:
      - 5000:5000
    volumes:
      - ./library:/mnt/library:ro
      - ./config:/home/node/camcam/config:rw