version: '3'
services:
  camcamdocker: 
    image: camcam:latest
    container_name: camcam
    user: node
    environment:
      - PORT=5000 #if not defined = 5000
      - MINUTES=2 #if not defined = 5
      - OFFSET=15 #if not defined = 0
    ports:
      - 5000:5000
    volumes:
      - ./library:/mnt/library:ro