Connection: 
  server: 
    hostname: host
    port: 5000
Generation: 
  minutes: 2
Versions: 
  v1:
    height: 1080
    width: 1920
    offset: 100
    shadow: true
    name: fhd
  v2: 
    height: 720 
    width: 1250
    offset: 0
    shadow: false
    name: main